sudo: false
dist: trusty

language: python

python:
    - 3.3
    - 3.4
    - 3.5

install:
    - mkdir neovim
    - curl -o neovim/nvim -L https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
    - chmod u+x neovim/nvim
    - pip install flake8

script:
    - PATH="$HOME/neovim:$PATH"
    - cd test
    - bash test.sh
    - flake8 --ignore E225,E231,E226,E402,E501,E731,F401,F403 test pythonx --exclude=colortbl.py
