sudo: required
dist: trusty

language: python

python:
    - 3.3
    - 3.4
    - 3.5

before_install:
    - sudo add-apt-repository ppa:neovim-ppa/stable -y
    - sudo apt-get update -y

install:
    # Install Neovim via Gist
    # https://gist.github.com/lambdalisue/0f461f6a91743895394e63a9a1c65232
    # - curl -sL https://gist.githubusercontent.com/lambdalisue/0f461f6a91743895394e63a9a1c65232/raw/install_nvim_for_ci.sh | bash
    - sudo apt-get install neovim
    - pip install neovim
    - pip install flake8

script:
    - PATH="$HOME/neovim/bin:$PATH"
    - cd test
    - bash test.sh
    - flake8 --ignore E225,E231,E226,E402,E501,E731,F401,F403 test pythonx --exclude=colortbl.py

