sudo: true
dist: trusty

language: python

python:
    - 3.3
    - 3.4
    - 3.5

install:
    - export NVIMDIR=$HOME/neovim/bin
    - mkdir -p $NVIMDIR
    - curl -o $NVIMDIR/nvim -L https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
    - chmod u+x $NVIMDIR/nvim
    - pip install neovim
    - pip install flake8

script:
    - PATH="$NVIMDIR:$PATH"
    - cd test
    - bash test.sh
    - flake8 --ignore E225,E231,E226,E402,E501,E731,F401,F403 test pythonx --exclude=colortbl.py
